import {createRun,start,room,types,question,answer,proceed,choose,drink,restore} from './engine.js';
import {questions} from './content.js';
import {createRenderer} from './renderer.js';
const $=id=>document.getElementById(id),escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function seed(){return Math.random().toString(36).slice(2,8).toUpperCase();}
let state;try{state=restore(localStorage.getItem('runespeak-run'));}catch{}state||=createRun(seed());let sound=false,selected=[];
function save(){try{localStorage.setItem('runespeak-run',JSON.stringify(state));}catch{}}
function sprite(n){return `<span class="sprite" data-tile="${n}" aria-hidden="true"></span>`;}
function paintSprites(){document.querySelectorAll('[data-tile]').forEach(el=>{const n=Number(el.dataset.tile);el.style.backgroundPosition=`-${n%12*32}px -${Math.floor(n/12)*32}px`;});}
function modal(html){$('modal-content').innerHTML=html;$('modal').showModal();paintSprites();}
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');setTimeout(()=>$('toast').classList.remove('visible'),2300);}
function tone(ok){if(!sound)return;try{const ac=new (window.AudioContext||window.webkitAudioContext)();const o=ac.createOscillator(),g=ac.createGain();o.connect(g);g.connect(ac.destination);o.type='sine';o.frequency.setValueAtTime(ok?440:180,ac.currentTime);o.frequency.exponentialRampToValueAtTime(ok?660:100,ac.currentTime+.18);g.gain.setValueAtTime(.07,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+.35);o.start();o.stop(ac.currentTime+.35);o.onended=()=>ac.close();}catch{}}
function speak(){if(!('speechSynthesis'in window)){toast('Pronunciation is not supported in this browser.');return;}speechSynthesis.cancel();const q=question(state),u=new SpeechSynthesisUtterance(q.spoken||q.es);u.lang='es-ES';u.rate=.85;speechSynthesis.speak(u);}
function act(fn){fn();selected=[];save();render();}
function render(){const rm=room(state),type=types[rm.type],finished=['won','lost'].includes(state.phase);$('health').textContent=`${state.hp} / 100`;$('hearts').textContent='♥'.repeat(Math.ceil(state.hp/20))+'♡'.repeat(5-Math.ceil(state.hp/20));$('health-fill').style.width=state.hp+'%';$('gold').textContent=state.gold;$('streak').innerHTML=`${state.streak} <small>correct</small>`;$('progress').innerHTML=`Room ${state.depth+1} <small>/ 9</small>`;$('potions').textContent=`${state.potions} left · +35 health`;$('potion').disabled=!state.potions||state.hp===100||finished||state.phase==='intro';$('seed-label').textContent=`SEED ${state.seed}`;$('biome').textContent=['THE WHISPERING CRYPT','THE MOSSBOUND HALLS','THE RUNIC DEPTHS'][Math.floor(state.depth/3)];$('room-label').textContent=`ROOM ${String(state.depth+1).padStart(2,'0')}`;$('room-name').textContent=state.phase==='intro'?'The forgotten entrance':type.name;$('encounter-type').textContent=state.phase==='intro'?'YOUR ADVENTURE BEGINS':type.label;$('scene-caption').textContent=state.phase==='doors'?'The runes fade. A new path opens.':type.description;$('challenge-kind').textContent=state.phase==='intro'?'YOUR FIRST EXPEDITION':finished?'EXPEDITION COMPLETE':question(state).category.toUpperCase();$('difficulty').textContent=rm.type==='boss'?`BOSS · ${state.bossStep+1} / 3`:'BEGINNER';
 $('doors').innerHTML=[0,1,2].map(i=>{const next=state.levels[Math.min(8,state.depth+1)][i],t=types[next.type];return `<button class="door" data-door="${i}" ${state.phase!=='doors'?'disabled':''}>${sprite(next.type==='boss'?110:next.type==='treasure'?89:next.type==='shrine'?32:next.type==='trap'?41:45)}<span><strong>${['Left','Middle','Right'][i]} passage</strong><small>${t.label} · ${t.damage} RISK</small></span></button>`;}).join('');$('door-hint').textContent=state.phase==='doors'?'Pick your next encounter':finished?'Adventure complete':'Clear this room to continue';$('door-title').textContent=state.depth===8?'The final chamber.':'Three doors. Your choice.';
 $('map').innerHTML=Array.from({length:9},(_,i)=>`<span class="node ${i===state.depth?'current':''} ${i<state.depth||state.phase==='won'?'done':''}" aria-label="Room ${i+1}${i===state.depth?', current':''}${i<state.depth?', cleared':''}">${i<state.depth||state.phase==='won'?'✓':i===8?'♜':i+1}</span>`).join('');
 const c=$('challenge');if(state.phase==='intro'){c.innerHTML=`<div class="rune-icon">ᚱ</div><h2 id="challenge-heading">Words are your magic.</h2><p class="lead">A forgotten dungeon. A book of spells.<br>And the Spanish words that will get you home.</p><ul class="rules"><li><b>01</b> Cast spells by answering Spanish challenges.</li><li><b>02</b> Choose doors, find treasure, and stay alive.</li><li><b>03</b> Reach room 9 and face the Rune Guardian.</li></ul><button class="primary" id="begin">Enter the dungeon →</button><div class="hint">Beginner friendly · about 5 minutes · no timer</div>`;$('begin').onclick=()=>act(()=>start(state));}
 else if(finished){const won=state.phase==='won';c.innerHTML=`<div class="rune-icon">${won?'✦':'☾'}</div><h2 id="challenge-heading">${won?'You found your way home.':'Even heroes need practice.'}</h2><p class="lead">${won?'The guardian falls silent. Your words have broken the final seal. ¡Muy bien!':'Your adventure ends here, but every word goes with you. Review your journal and try a new path.'}</p><div class="end-stats"><div><strong>${state.correct}/${state.attempts}</strong><span>correct spells</span></div><div><strong>${state.gold}</strong><span>gold found</span></div><div><strong>${state.bestStreak}</strong><span>best streak</span></div></div>${state.feedback?`<div class="feedback bad"><strong>The last rune: ${escape(state.feedback.answer)}</strong><p>${escape(state.feedback.explanation)}</p></div>`:''}<button class="primary" id="again">Start a new adventure →</button><button class="secondary" id="review">Review words from this run</button>`;$('again').onclick=()=>newAdventure();$('review').onclick=showJournal;}
 else if(state.phase==='doors'){c.innerHTML=`<div class="rune-icon">✦</div><h2 id="challenge-heading">Onward, adventurer.</h2><p class="lead">The room is clear. Choose one of the three passages to continue your expedition.</p><ul class="rules"><li><b>◈</b> Treasure: more gold and a bonus potion.</li><li><b>✧</b> Sanctuary: a correct spell restores 25 health.</li><li><b>⚔</b> Battle & traps: a wrong spell costs health.</li></ul><div class="hint">Door risks show health lost for a wrong answer.<br>You can also press 1, 2, or 3 to choose.</div>`;}
 else {const q=question(state);c.innerHTML=`<h2 id="challenge-heading">${rm.type==='boss'?'Break the guardian’s seal.':rm.type==='treasure'?'Unlock the treasure.':rm.type==='shrine'?'Awaken the healing rune.':rm.type==='trap'?'Disarm the ancient rune.':'Cast your next spell.'}</h2><p class="lead">${escape(q.prompt)}</p><div class="prompt-word" ${q.type==='choice'?'lang="es"':''}>${escape(q.es)}${q.type==='choice'?'<button class="listen" id="listen" aria-label="Hear Spanish pronunciation">♪ Hear pronunciation</button>':''}</div><div id="answer-area"></div>`;if($('listen'))$('listen').onclick=speak;if(state.phase==='feedback'){const f=state.feedback;$('answer-area').innerHTML=`<div class="feedback ${f.correct?'':'bad'}" role="status"><strong>${f.correct?'¡Muy bien! Spell successful.':'Not quite. Keep this word.'}</strong><p><b>${escape(f.answer)}</b></p><p>${escape(f.explanation)}</p><span class="reward">${f.correct?`+${f.gain} gold${f.heal?` · +${f.heal} health`:''}${rm.type==='treasure'?' · +1 potion':''}`:`−${f.damage} health · you can still move forward`}</span></div><button class="primary" id="continue">${rm.type==='boss'?(state.bossStep===2?'Leave the dungeon →':'Cast the next spell →'):'Reveal the passages →'}</button>`;$('continue').onclick=()=>act(()=>proceed(state));}else if(q.type==='choice'){$('answer-area').innerHTML=`<div class="answers">${q.options.map((o,i)=>`<button class="answer" data-answer="${i}"><kbd>${i+1}</kbd>${escape(o)}</button>`).join('')}</div><div class="hint">Choose a spell · keys 1–4 also work</div>`;document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>submit(q.options[Number(b.dataset.answer)]));}else renderTokens(q);}
 document.querySelectorAll('[data-door]').forEach(b=>b.onclick=()=>act(()=>choose(state,Number(b.dataset.door))));paintSprites();}
function renderTokens(q){$('answer-area').innerHTML=`<div class="sentence" lang="es" aria-live="polite">${selected.length?selected.map(i=>escape(q.options[i])).join(' '):'<span class="muted">Your spell goes here…</span>'}</div><div class="tokens">${q.options.map((w,i)=>`<button class="token" data-token="${i}" ${selected.includes(i)?'disabled':''} lang="es">${escape(w)}</button>`).join('')}</div><button class="secondary" id="clear-words">↶ Clear words</button><button class="primary" id="cast" ${selected.length!==q.options.length?'disabled':''}>Cast spell →</button>`;document.querySelectorAll('[data-token]').forEach(b=>b.onclick=()=>{selected.push(Number(b.dataset.token));renderTokens(q);});$('clear-words').onclick=()=>{selected=[];renderTokens(q);};$('cast').onclick=()=>submit(selected.map(i=>q.options[i]).join(' '));}
function submit(value){act(()=>answer(state,value));tone(state.feedback?.correct);}
function showJournal(){const unique=[...new Set(state.journal.map(x=>x.id))];modal(`<div class="eyebrow">YOUR WORD JOURNAL</div><h2>A little wiser, every room.</h2><p>${unique.length?`${state.correct} correct spells from ${state.attempts} challenges. Review your discoveries below.`:'Your discoveries will appear here after your first challenge.'}</p>${unique.map(id=>{const q=questions.find(q=>q.id===id);if(!q)return '';const entries=state.journal.filter(x=>x.id===id);return `<div class="journal-row"><div><b>${escape(q.type==='order'?q.answer:q.es)}</b><p>${escape(q.explanation)}</p></div><span>${entries.at(-1).correct?'✓ Learned':'↶ Practice'}</span></div>`;}).join('')}`);}
function newAdventure(){modal('<div class="eyebrow">A NEW PATH AWAITS</div><h2>Begin another adventure?</h2><p>This replaces the current run and its word journal. Enter a seed to replay the same dungeon, or leave it blank for a fresh one.</p><label for="seed-input">Dungeon seed (optional)</label><input id="seed-input" maxlength="32" placeholder="e.g. HOLA"><button class="primary" id="confirm-run">Enter a new dungeon →</button>');$('confirm-run').onclick=()=>{state=createRun($('seed-input').value.trim().toUpperCase()||seed());selected=[];save();$('modal').close();render();};}
$('new-run').onclick=newAdventure;$('journal').onclick=showJournal;$('potion').onclick=()=>{if(drink(state)){save();render();tone(true);toast('+35 health · potion used');}};$('sound').onclick=()=>{sound=!sound;$('sound').setAttribute('aria-pressed',String(sound));$('sound').setAttribute('aria-label',sound?'Disable sound':'Enable sound');toast(sound?'Spell sounds on':'Spell sounds off');};$('help').onclick=()=>modal('<div class="eyebrow">HOW TO PLAY</div><h2>Let your words lead the way.</h2><p>Clear nine rooms by answering a Spanish challenge in each. The final guardian has three challenges. Wrong answers cost health; correct answers earn gold. Reach the end with health remaining to win.</p><ul><li>Click an answer, or press 1–4. For word-order spells, click the words in sequence.</li><li>Read the explanation, then continue. Choose a door with the mouse or 1–3.</li><li>Press H or use Drink potion to recover 35 health.</li><li>Treasure rewards a potion; sanctuaries heal 25 health on a correct answer. A streak of 3+ adds 5 gold per correct spell.</li><li>Progress saves automatically in this browser. No timer, no account.</li></ul><p>Pronunciation uses your browser’s Spanish voice when available. Room layouts, encounters, and challenges vary by dungeon seed.</p>');$('credits').onclick=()=>modal('<div class="eyebrow">BUILT WITH OPEN ART</div><h2>Small pixels. Big adventures.</h2><p>Dungeon tiles, heroes, monsters, and items: <a href="https://kenney.nl/assets/tiny-dungeon" target="_blank" rel="noopener">Tiny Dungeon by Kenney</a>, released under <a href="https://creativecommons.org/publicdomain/zero/1.0/" target="_blank" rel="noopener">CC0 1.0</a>. Original license included with the game.</p><p>RuneSpeak code is MIT licensed. Spanish challenges and gameplay were created for this demo. Fonts: DM Sans and Fraunces from Google Fonts (SIL Open Font License); system fonts work offline.</p>');$('close-modal').onclick=()=>$('modal').close();$('modal').onclick=e=>{if(e.target===$('modal')&&e.offsetX<0)$('modal').close();};
document.addEventListener('keydown',e=>{if($('modal').open||e.ctrlKey||e.metaKey||e.altKey||['INPUT','TEXTAREA'].includes(e.target.tagName))return;if(e.key.toLowerCase()==='h')$('potion').click();const n=Number(e.key)-1;if(n>=0&&n<4){const b=document.querySelector(state.phase==='doors'?`[data-door="${n}"]`:`[data-answer="${n}"]`);b?.click();}if(e.key==='Enter'&&e.target===document.body){$('begin')?.click();$('continue')?.click();}});
render();createRenderer($('dungeon'),()=>state);
