import {questions} from './content.js';
export function rng(seed){let h=2166136261;for(const c of seed)h=Math.imul(h^c.charCodeAt(0),16777619);return()=>{h+=0x6D2B79F5;let t=Math.imul(h^h>>>15,1|h);t^=t+Math.imul(t^t>>>7,61|t);return((t^t>>>14)>>>0)/4294967296;};}
export function shuffle(a,r){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
export const types={battle:{name:'Monster lair',label:'BATTLE',tile:108,damage:20,gold:18,description:'A foe guards the way.'},treasure:{name:'Sealed treasury',label:'TREASURE',tile:89,damage:10,gold:30,description:'Words unlock its riches.'},shrine:{name:'Quiet sanctuary',label:'SANCTUARY',tile:32,damage:10,gold:10,description:'A healing rune awaits.'},trap:{name:'Hall of echoes',label:'TRAP',tile:41,damage:25,gold:24,description:'Watch your words.'},boss:{name:'The Rune Guardian',label:'FINAL ENCOUNTER',tile:110,damage:25,gold:60,description:'Three spells to break the seal.'}};
export function createRun(seed){const r=rng(seed);const deck=shuffle(questions.map(q=>q.id),r);const levels=Array.from({length:9},(_,depth)=>Array.from({length:3},(_,lane)=>{const type=depth===8?'boss':depth===0?'battle':shuffle(['battle','treasure','shrine','trap'],rng(`${seed}:${depth}`))[lane];return{type,variant:Math.floor(r()*3),qids:deck.slice((depth*3+lane)%deck.length,(depth*3+lane)%deck.length+3)};}));return{version:1,seed,levels,depth:0,lane:1,hp:100,gold:0,potions:2,streak:0,bestStreak:0,correct:0,attempts:0,phase:'intro',bossStep:0,journal:[],path:[],feedback:null};}
export const room=s=>s.levels[s.depth][s.lane];
export function question(s){const rm=room(s);const id=rm.qids[rm.type==='boss'?s.bossStep:0];const q=questions.find(q=>q.id===id);return {...q,options:shuffle(q.options,rng(`${s.seed}:${s.depth}:${s.lane}:${s.bossStep}:answers`))};}
export function start(s){if(s.phase==='intro')s.phase='challenge';return s;}
export function answer(s,value){if(s.phase!=='challenge')return s;const q=question(s),t=types[room(s).type];const correct=value===q.answer;s.attempts++;s.correct+=Number(correct);s.streak=correct?s.streak+1:0;s.bestStreak=Math.max(s.bestStreak,s.streak);let gain=0,heal=0;if(correct){gain=t.gold+(s.streak>=3?5:0);s.gold+=gain;if(room(s).type==='shrine'){heal=Math.min(25,100-s.hp);s.hp+=heal;}if(room(s).type==='treasure')s.potions++;}else{s.hp=Math.max(0,s.hp-t.damage);}s.journal.push({id:q.id,correct});s.feedback={correct,answer:q.answer,explanation:q.explanation,gain,heal,damage:correct?0:t.damage};s.phase=s.hp===0?'lost':'feedback';return s;}
export function proceed(s){if(s.phase!=='feedback')return s;s.feedback=null;if(room(s).type==='boss'){if(s.bossStep<2){s.bossStep++;s.phase='challenge';}else{s.phase='won';s.path.push(s.lane);}}else{s.phase='doors';}return s;}
export function choose(s,lane){if(s.phase!=='doors'||!Number.isInteger(lane)||lane<0||lane>2)return s;s.path.push(s.lane);s.depth++;s.lane=lane;s.phase='challenge';s.bossStep=0;return s;}
export function drink(s){if(s.potions<1||s.hp>=100||['intro','won','lost'].includes(s.phase))return false;s.potions--;s.hp=Math.min(100,s.hp+35);return true;}
export function restore(raw){try{const s=JSON.parse(raw);if(s.version!==1||typeof s.seed!=='string'||s.seed.length>32||!Number.isInteger(s.depth)||s.depth<0||s.depth>8||!Number.isInteger(s.lane)||s.lane<0||s.lane>2||!['intro','challenge','feedback','doors','won','lost'].includes(s.phase)||!Number.isFinite(s.hp)||s.hp<0||s.hp>100||!Number.isInteger(s.bossStep)||s.bossStep<0||s.bossStep>2||!Array.isArray(s.journal)||!Array.isArray(s.path))return null;for(const k of ['gold','potions','streak','bestStreak','correct','attempts'])if(!Number.isInteger(s[k])||s[k]<0)return null;s.levels=createRun(s.seed).levels;return s;}catch{return null;}}
