// Original A1 lessons, separate from the dungeon's seeded challenge bank.
export const lessonCatalog = {
 vocabulary:{title:'First words',description:'Everyday nouns, colors, and useful verbs.',symbol:'star',detail:'Vocabulary · 10 questions',unit:1,example:'La casa = the house',tip:'Learn nouns with el or la. The article helps you remember their gender.'},
 greetings:{title:'Say hello',description:'Greet someone, introduce yourself, and say goodbye.',symbol:'sound',detail:'Conversation · 10 questions',unit:1,example:'Me llamo Ana. = My name is Ana.',tip:'Use ¿Cómo estás? with a friend. Buenos días means good morning.'},
 matching:{title:'Word connections',description:'Connect Spanish words to their English meanings.',symbol:'bolt',detail:'Matching · 6 rounds',unit:1,example:'el libro ↔ the book',tip:'Choose a Spanish word, then its English partner. Match all four pairs.'},
 grammar:{title:'Make a sentence',description:'Practice articles, adjective agreement, and present-tense verbs.',symbol:'book',detail:'Grammar · 10 questions',unit:2,example:'Nosotros bebemos agua. = We drink water.',tip:'The verb changes with the subject: yo hablo, tú hablas, nosotros hablamos.'},
 sentences:{title:'Build your own',description:'Put Spanish words in order to express everyday ideas.',symbol:'book',detail:'Word order · 10 questions',unit:2,example:'Yo quiero un café. = I want a coffee.',tip:'Start with who is speaking, then the action. Adjectives often follow nouns.'},
 listening:{title:'Listen closely',description:'Hear a short phrase and choose the words you heard.',symbol:'sound',detail:'Listening · 10 questions',unit:2,example:'Listen → Buenos días',tip:'Listen normally or slowly. You can reveal the transcript if audio is unavailable.'},
 food:{title:'At the café',description:'Order food, ask for water, and request the bill politely.',symbol:'star',detail:'Food & conversation · 10 questions',unit:3,example:'Un café, por favor. = A coffee, please.',tip:'Por favor means please. Quiero means I want; quisiera is a polite I would like.'},
 stories:{title:'A morning with Ana',description:'Read a short story and find the meaning in context.',symbol:'book',detail:'Reading · 6 questions',unit:3,example:'Ana tiene un gato. El gato se llama Sol.',tip:'Read for the main idea first. Look for names, familiar nouns, and repeated verbs.'},
 mixed:{title:'Put it all together',description:'Review vocabulary, grammar, and sentence building.',symbol:'trophy',detail:'Mixed practice · 10 questions',unit:3,example:'Un poco cada día. = A little every day.',tip:'Revisit earlier lessons too. A short review helps new words stick.'},
};
const words=[['el café','coffee'],['la leche','milk'],['la mesa','the table'],['la silla','the chair'],['la escuela','the school'],['la ciudad','the city'],['el tren','the train'],['la tienda','the shop'],['la manzana','the apple'],['la familia','the family'],['el hermano','the brother'],['la hermana','the sister'],['hoy','today'],['mañana','tomorrow'],['azul','blue'],['blanco','white'],['aprender','to learn'],['escribir','to write'],['leer','to read'],['hablar','to speak'],['el desayuno','breakfast'],['el queso','cheese'],['el arroz','rice'],['la fruta','fruit']];
const choice=(id,es,answer,wrong,explanation,extra={})=>({id,type:'choice',es,answer,options:[answer,...wrong],explanation,...extra});
export const extraVocabulary=words.map(([es,en],i)=>choice('v-extra-'+i,es,en,[5,11,17].map(n=>words[(i+n)%words.length][1]),`${es} means ${en}.`,{category:'Everyday words'}));
const grammarRows=[
 ['Yo ___ café.','bebo',['bebes','bebe','beben'],'Yo bebo means I drink.'],['Tú ___ un libro.','lees',['leo','lee','leemos'],'Tú lees means you read.'],['Ella ___ español.','habla',['hablo','hablas','hablan'],'Ella habla means she speaks.'],['Nosotros ___ en casa.','estamos',['estoy','estás','está'],'Nosotros estamos means we are. Use estar for location.'],['Las manzanas son ___.','rojas',['rojo','roja','rojos'],'Manzanas is feminine plural, so use rojas.'],['___ mesa es grande.','La',['El','Los','Las'],'Mesa is feminine singular: la mesa.'],['Tengo ___ hermanos.','dos',['un','una','el'],'Dos hermanos means two brothers or siblings.'],['Mi hermana ___ leche.','bebe',['bebo','bebes','bebemos'],'Mi hermana is third-person singular: bebe.'],['Quiero ___ español.','aprender',['aprendo','aprendes','aprenden'],'After quiero, use an infinitive: aprender.'],['Los libros ___ azules.','son',['es','soy','eres'],'Los libros is plural: son. Azul becomes azules in the plural.']];
export const extraGrammar=grammarRows.map((r,i)=>choice('g-extra-'+i,...r,{category:'Everyday grammar'}));
const greetings=[
 ['Someone says “Hola”. What is a friendly reply?','¡Hola!',['La mesa.','Dos cafés.','El perro.'],'Hola means hello.'],['How do you say “Good morning”?','Buenos días',['Buenas noches','Hasta mañana','De nada'],'Buenos días is a morning greeting.'],['How do you say “My name is Ana”?','Me llamo Ana.',['Tengo una mesa.','Ana tiene café.','Soy de Madrid.'],'Me llamo introduces your name.'],['A friend asks “¿Cómo estás?” How can you say “Fine, thanks”?','Bien, gracias.',['Hasta luego.','Por favor.','Me llamo Luis.'],'Bien, gracias means fine, thank you.'],['How do you say “Please”?','Por favor',['Gracias','Adiós','Hola'],'Use por favor when making a polite request.'],['Someone helps you. What means “Thank you”?','Gracias',['Hola','Lo siento','Hasta mañana'],'Gracias means thank you.'],['Someone says “Gracias”. What means “You’re welcome”?','De nada',['Buenas tardes','Mucho gusto','Adiós'],'De nada is a common reply to gracias.'],['How do you say “See you tomorrow”?','Hasta mañana',['Buenos días','Buenas noches','Por favor'],'Hasta mañana means see you tomorrow.'],['You meet someone for the first time. What means “Nice to meet you”?','Mucho gusto',['De nada','Hasta luego','Lo siento'],'Mucho gusto is a friendly response to an introduction.'],['How do you ask a friend’s name?','¿Cómo te llamas?',['¿Dónde está la mesa?','¿Cuánto cuesta?','¿Qué hora es?'],'¿Cómo te llamas? asks what your name is.']];
const food=[
 ['How do you order “A coffee, please”?','Un café, por favor.',['Una mesa azul.','El café está aquí.','Tengo un hermano.'],'Un café, por favor is a simple, polite order.'],['What does “Quiero agua” mean?','I want water',['I drink milk','I want bread','I have coffee'],'Quiero means I want; agua means water.'],['How do you ask for the bill?','La cuenta, por favor.',['Buenos días.','Me llamo Ana.','El gato es blanco.'],'La cuenta means the bill in a café or restaurant.'],['What is “el desayuno”?','breakfast',['dinner','the bill','the table'],'El desayuno is breakfast.'],['What does “sin azúcar” mean?','without sugar',['with milk','more water','a little bread'],'Sin means without; azúcar means sugar.'],['What does “con leche” mean?','with milk',['without sugar','with bread','without water'],'Con means with; leche means milk.'],['What does “¿Cuánto cuesta?” ask?','How much does it cost?',['Where is the café?','What is your name?','Do you want water?'],'Cuánto asks how much; cuesta means it costs.'],['How do you say “I would like bread”?','Quisiera pan.',['Bebo leche.','Tengo queso.','Soy Ana.'],'Quisiera is a polite way to say I would like.'],['What does “Tengo hambre” mean?','I am hungry',['I am thirsty','I am tired','I am happy'],'Spanish uses tener hambre, literally to have hunger.'],['What does “Tengo sed” mean?','I am thirsty',['I am hungry','I am cold','I am late'],'Spanish uses tener sed, literally to have thirst.']];
const contextual=(rows,prefix)=>rows.map((r,i)=>choice(prefix+i,...r,{lessonType:'conversation',prompt:r[0],spoken:r[1]}));
const phrases=['Buenos días','Me llamo Ana','Quiero agua','Un café, por favor','Tengo un libro','La casa es grande','Mi hermana bebe leche','Nosotros hablamos español','Hasta mañana','El gato es blanco'];
const listening=phrases.map((es,i)=>choice('listen-'+i,es,es,[2,5,7].map(n=>phrases[(i+n)%phrases.length]),`You heard: ${es}.`,{lessonType:'listening',spoken:es}));
const orderRows=[['I want a coffee.','Yo quiero un café'],['My sister reads a book.','Mi hermana lee un libro'],['We speak Spanish.','Nosotros hablamos español'],['The table is white.','La mesa es blanca'],['I drink water.','Yo bebo agua'],['The apples are red.','Las manzanas son rojas'],['My name is Ana.','Me llamo Ana'],['I have two brothers.','Tengo dos hermanos'],['A coffee with milk, please.','Un café con leche por favor'],['The cat is at home.','El gato está en casa']];
const orders=orderRows.map(([en,es],i)=>({id:'order-new-'+i,type:'order',es,answer:es,options:es.split(' '),prompt:`Build the Spanish for “${en}”`,explanation:`${es} = ${en}`}));
const storyRows=[
 ['Ana vive en Madrid. Tiene un gato. El gato se llama Sol.','Where does Ana live?','Madrid',['Lima','Bogotá','Sevilla'],'Vive en Madrid means she lives in Madrid.'],
 ['Ana vive en Madrid. Tiene un gato. El gato se llama Sol.','What is the cat’s name?','Sol',['Ana','Luna','Madrid'],'El gato se llama Sol means the cat is named Sol.'],
 ['Por la mañana, Ana bebe café con leche. Sol bebe agua.','What does Ana drink?','Coffee with milk',['Water','Tea','Juice'],'Ana bebe café con leche: Ana drinks coffee with milk.'],
 ['Por la mañana, Ana bebe café con leche. Sol bebe agua.','Who drinks water?','Sol',['Ana','Ana’s brother','Ana’s friend'],'Sol bebe agua: Sol drinks water.'],
 ['Ana va a un café. Quiere pan. Dice: «Pan, por favor».','What does Ana want?','Bread',['Rice','Cheese','An apple'],'Quiere pan means she wants bread.'],
 ['Ana vuelve a casa. Lee un libro. Sol está en una silla.','Where is Sol?','On a chair',['At the café','On a table','At school'],'Sol está en una silla means Sol is on a chair.']];
const stories=storyRows.map(([es,prompt,answer,wrong,explanation],i)=>choice('story-'+i,es,answer,wrong,explanation,{lessonType:'reading',prompt,spoken:es}));
const matching=Array.from({length:6},(_,i)=>{const pairs=words.slice(i*4,i*4+4).map(([es,en])=>({es,en}));return {id:'match-'+i,type:'matching',es:'Match the word pairs',answer:'matched',options:pairs.map(p=>p.en),pairs,explanation:pairs.map(p=>`${p.es} = ${p.en}`).join(' · ')};});
export const lessonPools={greetings:contextual(greetings,'greeting-'),food:contextual(food,'cafe-'),listening,sentences:orders,stories,matching};
export const learningQuestions=[...extraVocabulary,...extraGrammar,...Object.values(lessonPools).flat()];
