// Approved monster variants, grouped by their home dungeon.
export const monsterEnemies = [
  {"id":"candlewisp","name":"Candlewisp","monster":"candlewisp","family":"candlewisp","dungeon":"crypt","tile":122},
  {"id":"candlewisp-votive","name":"Votive Candlewisp","monster":"candlewisp-votive","family":"candlewisp","dungeon":"crypt","tile":122},
  {"id":"candlewisp-vigil","name":"Vigil Candlewisp","monster":"candlewisp-vigil","family":"candlewisp","dungeon":"crypt","tile":122},
  {"id":"vault-mimic","name":"Vault Mimic","monster":"vault-mimic","family":"vault-mimic","dungeon":"crypt","tile":122},
  {"id":"vault-mimic-coffer","name":"Iron Coffer Mimic","monster":"vault-mimic-coffer","family":"vault-mimic","dungeon":"crypt","tile":122},
  {"id":"vault-mimic-reliquary","name":"Royal Reliquary Mimic","monster":"vault-mimic-reliquary","family":"vault-mimic","dungeon":"crypt","tile":122},
  {"id":"belfry-bat-dusk","name":"Dusk Bat","monster":"belfry-bat-dusk","family":"belfry-bat","dungeon":"crypt","tile":122},
  {"id":"belfry-bat-echo","name":"Echo Bat","monster":"belfry-bat-echo","family":"belfry-bat","dungeon":"crypt","tile":122},
  {"id":"belfry-bat","name":"Belfry Bat","monster":"belfry-bat","family":"belfry-bat","dungeon":"crypt","tile":122},
  {"id":"sporecap","name":"Sporecap","monster":"sporecap","family":"sporecap","dungeon":"moss","tile":122},
  {"id":"sporecap-inkcap","name":"Inkcap Sporecap","monster":"sporecap-inkcap","family":"sporecap","dungeon":"moss","tile":122},
  {"id":"sporecap-puffball","name":"Puffball Sporecap","monster":"sporecap-puffball","family":"sporecap","dungeon":"moss","tile":122},
  {"id":"bramblekin","name":"Bramblekin","monster":"bramblekin","family":"bramblekin","dungeon":"moss","tile":122},
  {"id":"bramblekin-thorn","name":"Thorn Bramblekin","monster":"bramblekin-thorn","family":"bramblekin","dungeon":"moss","tile":122},
  {"id":"bramblekin-moss","name":"Mossback Bramblekin","monster":"bramblekin-moss","family":"bramblekin","dungeon":"moss","tile":122},
  {"id":"lantern-snail","name":"Lantern Snail","monster":"lantern-snail","family":"lantern-snail","dungeon":"moss","tile":122},
  {"id":"lantern-snail-moon","name":"Moon Lantern Snail","monster":"lantern-snail-moon","family":"lantern-snail","dungeon":"moss","tile":122},
  {"id":"lantern-snail-ember","name":"Ember Lantern Snail","monster":"lantern-snail-ember","family":"lantern-snail","dungeon":"moss","tile":122},
  {"id":"runestone-golem","name":"Runestone Golem","monster":"runestone-golem","family":"runestone-golem","dungeon":"runic","tile":122},
  {"id":"runestone-golem-seal","name":"Sealkeeper Golem","monster":"runestone-golem-seal","family":"runestone-golem","dungeon":"runic","tile":122},
  {"id":"runestone-golem-amethyst","name":"Amethyst Golem","monster":"runestone-golem-amethyst","family":"runestone-golem","dungeon":"runic","tile":122},
  {"id":"crystal-scarab","name":"Crystal Scarab","monster":"crystal-scarab","family":"crystal-scarab","dungeon":"runic","tile":122},
  {"id":"crystal-scarab-jade","name":"Jade Crystal Scarab","monster":"crystal-scarab-jade","family":"crystal-scarab","dungeon":"runic","tile":122},
  {"id":"crystal-scarab-sunstone","name":"Sunstone Crystal Scarab","monster":"crystal-scarab-sunstone","family":"crystal-scarab","dungeon":"runic","tile":122},
  {"id":"spellbook-snapper","name":"Spellbook Snapper","monster":"spellbook-snapper","family":"spellbook-snapper","dungeon":"runic","tile":122},
  {"id":"spellbook-snapper-atlas","name":"Atlas Spellbook Snapper","monster":"spellbook-snapper-atlas","family":"spellbook-snapper","dungeon":"runic","tile":122},
  {"id":"spellbook-snapper-grimoire","name":"Grimoire Spellbook Snapper","monster":"spellbook-snapper-grimoire","family":"spellbook-snapper","dungeon":"runic","tile":122},
];
